shims:
  disableAll: true
  fc:
    enabled: true
    containerd:
      snapshotter: devmapper
    runtimeClass:
      overhead:
        cpu: "0"
runtimeClasses:
  enabled: true
  createDefault: false
  overheadEnabled: true
defaultShim:
  amd64: fc
nodeSelector:
  kubernetes.azure.com/agentpool: __FIRECRACKER_NODEPOOL_NAME__
tolerations:
  - operator: Exists
