metricsEndpoints:
  - indexer:
      type: local
      metricsDirectory: "{{.metricsDirectory}}"
      createTarball: false
global:
  gc: {{.gc}}
  measurements:
    - name: podLatency
jobs:
  - name: runtimeclass-pod-latency
    jobIterations: {{.podCount}}
    qps: {{.qps}}
    burst: {{.burst}}
    namespace: "{{.namespace}}"
    namespacedIterations: false
    cleanup: {{.cleanup}}
    waitWhenFinished: {{.waitWhenFinished}}
    podWait: {{.podWait}}
    objects:
      - objectTemplate: "{{.podTemplatePath}}"
        replicas: {{.podReplicas}}
        inputVars:
          runtimeClass: "{{.runtimeClass}}"
          containerImage: "{{.podImage}}"
          command:
{{- if .podCommand }}
{{- range .podCommand }}
            - {{ printf "%q" . }}
{{- end }}
{{- else }}
            []
{{- end }}
          cpuRequest: "{{.podCpuRequest}}"
          memoryRequest: "{{.podMemoryRequest}}"
          cpuLimit: "{{.podCpuLimit}}"
          memoryLimit: "{{.podMemoryLimit}}"
          nodeSelector:
{{- if .nodeSelector }}
{{- range $key, $value := .nodeSelector }}
            {{ $key }}: {{ printf "%q" $value }}
{{- end }}
{{- else }}
            {}
{{- end }}
          tolerations:
{{- if .tolerations }}
{{- range .tolerations }}
            - key: {{ printf "%q" .key }}
              operator: {{ printf "%q" .operator }}
{{- if .value }}
              value: {{ printf "%q" .value }}
{{- end }}
              effect: {{ printf "%q" .effect }}
{{- end }}
{{- else }}
            []
{{- end }}
