- query: '{__name__=~"kubelet_run_podsandbox_duration_seconds(_bucket|_sum|_count)?"}'
  metricName: kubeletRunPodSandboxDurationSecondsRaw
- query: '{__name__=~"kubelet_pod_start_sli_duration_seconds(_bucket|_sum|_count)?"}'
  metricName: kubeletPodStartSliDurationSecondsRaw
- query: '{__name__=~"kubelet_pod_start_total_duration_seconds(_bucket|_sum|_count)?"}'
  metricName: kubeletPodStartTotalDurationSecondsRaw
